openapi: 3.0.3
info:
  title: Players Management System
  version: 1.0.0
servers:
  - url: https://localhost:8080api
paths:
  /player:
    get:
      operationId: getPlayers
      summary: Get all players
      responses:
        200:
          description: Get all players successfully
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/Player'
              example: [{ "id": 1, "firstName": "Francesco", "lastName": "Totti", "team": "Roma", "position": "midfielder" }, { "id": 2, "firstName": "Alessandro", "lastName": "Del Piero", "team": "Juventus", "position": "forward" }]
  /player/{id}:
    get:
      operationId: getPlayerById
      summary: Get a player by id
      parameters:
        - name: id
          in: path
          description: "Id of the Player"
          required: true
          schema:
            type: string
      responses:
        200:
          description: Get player information successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Player'
              example: { "id": 1, "firstName": "Francesco", "lastName": "Totti", "team": "Roma", "position": "midfielder" }
    delete:
      operationId: deletePlayerById
      summary: Delete a player by id
      parameters:
        - name: id
          in: path
          description: "Id of the Player"
          required: true
          schema:
            type: string
      responses:
        200:
          description: Delete player information successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example: { "message": "Player deleted!"}
components:
  schemas:
    Player:
      type: object
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
        lastName:
          type: string
        team:
          type: string
        position:
          type: string
    Response:
      type: object
      properties:
        message:
          type: string